dataset_dict = {
    "Human-Kidney-RNA": "UP_HK-RNA",
    "Human-Kidney-ATAC": "UP_HK-ATAC",
    "Mouse-MOp-RNA": "Yao-2021-RNA",
    "CL_RNA": "CL_RNA",
    "CL_ATAC": "CL_ATAC",
    "PBMC_Time": "pbmc_seurat_v4",
    "PBMC_Sub": "pbmc_seurat_v4",
    "HGSOC": "external_slyper_natmed_2020_32405060",
    "mice_zebrafish": "mouse_heart_pancreas",
    "Zeisel_p20_p29": "Zeisel_2018_p20_p29",
    "Liver_Human_Mouse": "liver_human_mouse_merged",
    "TMS_Thymus": "tabula-muris-senis-droplet-processed-official-annotations-Thymus",
    "TMS-facs-Trachea": "TMS-facs-Trachea",
    "peng": "external_peng_cellres_2019_31273297",
    "bassez": "external_bassez_natmed_2021_33958794",
    "BoneMarrowA_BoneMarrowB": "BoneMarrowA_BoneMarrowB",
    "TMS-facs-GAT": "TMS-facs-GAT",
    "Cao_2020_Eye": "Cao_2020_Eye",
    "TS_Skin": "TS_Skin",
    "cd34_multiome_rna": "cd34_multiome_rna",
    "bm_multiome_rna": "bm_multiome_rna",
    "Ma_RNA": "Ma-2020-RNA",
    "Cao_2020_Pancreas": "Cao_2020_Pancreas",
    "Alemany_Fin": "Alemany_Fin",
    "PBMC_ATAC_ASAP_seq": "PBMC_ATAC_ASAP_seq",
    "HNSCC_RNA": "hnscc_rna_test_split_rawX",
    "HNSCC_ADT": "hnscc_adt_test_split",
}
ood_setting_dict = {
    "HNSCC_RNA": {
        "modalities": ["RNA"],
        "batches": [],
        "setting1": {
            "info": "",
            "cell_type_key": "cell_type",
            "batch_key": "split",
            "ood_type": ['Macrophage', 'CD8_Exhausted'],
            "remove_type": [],
            "train_batch": ['train'],
            "test_batch": ['test'],
        },
    },
    "HNSCC_ADT": {
        "modalities": ["ADT"],
        "batches": [],
        "setting1": {
            "info": "",
            "cell_type_key": "cell_type",
            "batch_key": "split",
            "ood_type": ['Macrophage', 'CD8_Exhausted'],
            "remove_type": [],
            "train_batch": ['train'],
            "test_batch": ['test'],
        },
    },
    "Human-Kidney-RNA": {
        "modalities": ["RNA", "ATAC"],
        "batches": ['e0def004-9e30-4a3b-9a65-007110f3a1f2', 'f6c0f811-2fb8-4989-b796-37c14b055517', '5028f75a-8c09-4155-a232-ad7dbfa6042e', '8c570254-4bef-48d8-bd79-c812f60835a5', '8213a3f7-2437-4e8a-b836-caec33df901d'],
        "setting1": {
            "cell_type_key": "cell_type",
            "batch_key": "batch",
            "ood_type": ['PODO', 'TAL', 'PEC'],
            "remove_type": [],
            "split_type": "batch",
            "train_batch": ['e0def004-9e30-4a3b-9a65-007110f3a1f2', 'f6c0f811-2fb8-4989-b796-37c14b055517', '5028f75a-8c09-4155-a232-ad7dbfa6042e'],
            "test_batch": ['8c570254-4bef-48d8-bd79-c812f60835a5', '8213a3f7-2437-4e8a-b836-caec33df901d']
        },
    },
    "Human-Kidney-ATAC": {
        "modalities": ["RNA", "ATAC"],
        "batches": ['e0def004-9e30-4a3b-9a65-007110f3a1f2', 'f6c0f811-2fb8-4989-b796-37c14b055517', '5028f75a-8c09-4155-a232-ad7dbfa6042e', '8c570254-4bef-48d8-bd79-c812f60835a5', '8213a3f7-2437-4e8a-b836-caec33df901d'],
        "setting1": {
            "cell_type_key": "cell_type",
            "batch_key": "batch",
            "ood_type": ['PODO', 'TAL', 'PEC'],
            "remove_type": [],
            "split_type": "batch",
            "train_batch": ['e0def004-9e30-4a3b-9a65-007110f3a1f2', 'f6c0f811-2fb8-4989-b796-37c14b055517', '5028f75a-8c09-4155-a232-ad7dbfa6042e'],
            "test_batch": ['8c570254-4bef-48d8-bd79-c812f60835a5', '8213a3f7-2437-4e8a-b836-caec33df901d']
        },
    },
    "CL_RNA": {
        "modalities": ["RNA"],
        "setting1": {
            "info": "",
            "cell_type_key": "cell_type",
            "batch_key": "batch",
            "ood_type": ['HCT116', 'HeLa-S3', 'K562'],
            "remove_type": [],
            "train_batch": ['Batch3', 'Batch4'],
            "test_batch": ['Batch1', 'Batch2']
        },
    },
    "CL_ATAC": {
        "modalities": ["ATAC"],
        "setting1": {
            "info": "",
            "cell_type_key": "cell_type",
            "batch_key": "batch",
            "ood_type": ['HCT116', 'HeLa-S3', 'K562'],
            "remove_type": [],
            "train_batch": ['Batch3', 'Batch4'],
            "test_batch": ['Batch1', 'Batch2']
        },
    },
    "TS_Skin": {
        "modalities": ["RNA"],
        "setting1": {
            "info": "",
            "cell_type_key": "cell_ontology_class",
            "batch_key": "donor",
            "ood_type": ['endothelial cell', 'cell of skeletal muscle', 'smooth muscle cell', 'muscle cell', 'stromal cell'],
            "remove_type": [],
            "train_batch": ['TSP10'],
            "test_batch": ['TSP14']
        },
    },
    "PBMC_Time": {
        "modalities": ["RNA"],
        "setting1": {
            "info": "",
            "cell_type_key": "celltype.l2",
            "batch_key": "time",
            "ood_type": ['CD4 TCM', 'NK', 'CD8 TEM'],
            "remove_type": [],
            "train_batch": ['0', '3'],
            "test_batch": ['7'],
        },
    },
    "PBMC_Sub": {
        "modalities": ["RNA"],
        "setting1": {
            "info": "",
            "cell_type_key": "sub_cell_type",
            "batch_key": "time",
            "ood_type": ['B naive', 'B memory', 'B intermediate'],
            "remove_type": [],
            "train_batch": ['0', '3'],
            "test_batch": ['7'],
        },
    },
    "Zeisel_p20_p29": {
        "modalities": ["RNA"],
        "setting1": {
            "info": "",
            "cell_type_key": "cell_type1",
            "batch_key": "age",
            "ood_type": ['Olfactory ensheathing cells', 'Olfactory inhibitory neurons', 'Dentate gyrus radial glia-like cells', 'Telencephalon inhibitory interneurons', 'Telencephalon projecting excitatory neurons', 'Telencephalon projecting inhibitory neurons', 'Non-glutamatergic neuroblasts'],
            "remove_type": [],
            "train_batch": ['p20'],
            "test_batch": ['p29'],
        },
    },
    "Liver_Human_Monkey": {
        "modalities": ["RNA"],
        "setting1": {
            "info": "只有一类重合",
            "cell_type_key": "cell_ontology_class",
            "batch_key": "species",
            "ood_type": ['Macrophages', 'Endothelial', 'fibroblasts', 'Cholangio'],
            "remove_type": [],
            "train_batch": ['monkey'],
            "test_batch": ['human'],
        },
    },
    "HGSOC": {
        "modalities": ["RNA"],
        "setting1": {
            "info": "",
            "cell_type_key": "standard_true_celltype",
            "batch_key": "split",
            "ood_type": ['Cancer_cells'],
            "remove_type": [],
            "train_batch": ['train'],
            "test_batch": ['test'],
        },
    },
    "mice_zebrafish": {
        "modalities": ["RNA"],
        "setting1": {
            "info": "",
            "cell_type_key": "cell_type",
            "batch_key": "tissue",
            "ood_type": ['exocrine cell', 'type B pancreatic cell', 'pancreatic A cell', 'pancreatic D cell', 'hepatic stellate cell', 'pancreatic PP cell', 'Schwann cell'],  # , 'other T'
            "remove_type": ['Kupffer cell', 'hepatocyte', 'neutrophil', 'mature NK T cell', 'kidney tubule cell', 'unknown'],
            "train_batch": ['heart'],
            "test_batch": ['pancreas'],
        },
    },
    "TMS_Thymus": {
        "modalities": ["RNA"],
        "setting1": {
            "info": "",
            "cell_type_key": "cell_ontology_class",
            "batch_key": "sex",
            "ood_type": ['double negative T cell', 'immature T cell'],
            "remove_type": [],
            "train_batch": ['male'],
            "test_batch": ['female'],
        },
    },
    "Mouse-MOp-RNA": {
        "modalities": ["RNA"],
        "setting1": {
            "info": "",
            "cell_type_key": "cell_type",
            "batch_key": "Seq_batch",
            "ood_type": ['NP', 'Sst', 'Vip'],
            "remove_type": [],
            "train_batch": ['RTX-841', 'RTX-842'],
            "test_batch": ['RTX-850'],
        },
    },
    "TMS-facs-Trachea": {
        "modalities": ["RNA"],
        "setting1": {
            "info": "",
            "cell_type_key": "cell_ontology_class",
            "batch_key": "age",
            "ood_type": ['macrophage', 'fibroblast', 'T cell'],
            "remove_type": [],
            "train_batch": ['3m', '18m'],
            "test_batch": ['24m'],
        },
    },
    "peng": {
        "modalities": ["RNA"],
        "setting1": {
            "info": "",
            "cell_type_key": "standard_true_celltype",
            "batch_key": "split",
            "ood_type": ['Cancer_cells'],
            "remove_type": [],
            "train_batch": ['train'],
            "test_batch": ['test'],
        },
    },
    "bassez": {
        "modalities": ["RNA"],
        "setting1": {
            "info": "",
            "cell_type_key": "standard_true_celltype",
            "batch_key": "split",
            "ood_type": ['Cancer_cells'],
            "remove_type": [],
            "train_batch": ['train'],
            "test_batch": ['test'],
        },
    },
    "BoneMarrowA_BoneMarrowB": {
        "modalities": ["RNA"],
        "setting1": {
            "info": "",
            "cell_type_key": "CellType",
            "batch_key": "Batch",
            "ood_type": ['Erythroblasts', 'Monocytes', 'Immature B cells'],
            "remove_type": [],
            "train_batch": ['BoneMarrowB'],
            "test_batch": ['BoneMarrowA'],
        },
    },
    "TMS-facs-GAT": {
        "modalities": ["RNA"],
        "setting1": {
            "info": "",
            "cell_type_key": "cell_ontology_class",
            "batch_key": "age",
            "ood_type": ['mesenchymal stem cell of adipose', 'B cell', 'myeloid cell'],
            "remove_type": [],
            "train_batch": ['3m', '18m'],
            "test_batch": ['24m'],
        },
    },
    "Cao_2020_Eye": {
        "modalities": ["RNA"],
        "setting1": {
            "info": "",
            "cell_type_key": "cell_ontology_class",
            "batch_key": "Batch",
            "ood_type": ['amacrine cell', 'retinal ganglion cell', 'retina horizontal cell'],
            "remove_type": ['nan'],
            "train_batch": ['2', '4'],
            "test_batch": ['10'],
        },
    },
    "cd34_multiome_rna": {
        "modalities": ["RNA"],
        "setting1": {
            "info": "",
            "cell_type_key": "celltype",
            "batch_key": "batch",
            "ood_type": ['HSC', 'Mono', 'Ery'],
            "remove_type": [],
            "train_batch": ['0'],
            "test_batch": ['1'],
        },
    },
    "bm_multiome_rna": {
        "modalities": ["RNA"],
        "setting1": {
            "info": "",
            "cell_type_key": "celltype",
            "batch_key": "batch",
            "ood_type": ['Mono', 'Mono2', 'MonoPre'],
            "remove_type": [],
            "train_batch": ['0'],
            "test_batch": ['1'],
        },
    },
    "TS_Thymus": {
        "modalities": ["RNA"],
        "setting1": {
            "info": "",
            "cell_type_key": "cell_ontology_class",
            "batch_key": "donor",
            "ood_type": ['b cell', 'cd8-positive, alpha-beta cytotoxic t cell', 'dn1 thymic pro-t cell', 'dn3 thymocyte', 'dn4 thymocyte', 'innate lymphoid cell', 'myeloid dendritic cell', 'naive regulatory t cell', 't follicular helper cell'],  #
            "remove_type": [],
            "train_batch": ['TSP2'],
            "test_batch": ['TSP14'],
        },
    },
    "Cao_2020_Pancreas": {
        "modalities": ["RNA"],
        "setting1": {
            "info": "",
            "cell_type_key": "cell_ontology_class",
            "batch_key": "donor",
            "ood_type": ['blood vessel endothelial cell', 'leukocyte', 'stromal cell of pancreas'],
            "remove_type": [],
            "train_batch": ['H27870', 'H27876'],
            "test_batch": ['H27948'],
        },
    },
    "Alemany_Fin": {
        "modalities": ["RNA"],
        "setting1": {
            "info": "",
            "cell_type_key": "cell_ontology_class",
            "batch_key": "donor",
            "ood_type": ['fibroblast', 'leukocyte'],
            "remove_type": [],
            "train_batch": ['R4'],
            "test_batch": ['R5'],
        },
    },
    "PBMC_ATAC_ASAP_seq": {
        "modalities": ["ATAC"],
        "setting1": {
            "info": "",
            "cell_type_key": "CellType",
            "batch_key": "split",
            "ood_type": ['Monocytes', 'B', 'NK', 'Effector CD4+ T'],
            "remove_type": [],
            "train_batch": ['train'],
            "test_batch": ['test'],
        },
    },
}